//! JSON I/O: parse block.json + witness.json into StatelessInput.
//!
//! The JSON formats:
//!
//!   block.json (any of these is accepted):
//!     { "result": "0x<hex RLP>" }  — raw JSON-RPC response from debug_getRawBlock
//!     { "block":  "0x<hex RLP>" }  — generated by `zig build gen-example`
//!
//!   witness.json:
//!     { "state":   ["0x<hex>", ...],   — flat pool of RLP trie node preimages
//!       "codes":   ["0x<hex>", ...],   — contract bytecodes
//!       "keys":    ["0x<hex>", ...],   — 20-byte addrs or 52-byte addr+slot
//!       "headers": ["0x<hex>", ...] }  — RLP block headers for BLOCKHASH
//!
//! All hex-decoded byte slices are allocated from the provided allocator.

const std    = @import("std");
const primitives = @import("primitives");
const input  = @import("input");
const mpt    = @import("mpt");

// ─── JSON schema structs ───────────────────────────────────────────────────────

/// Accepts either:
///   {"result":"0x<rlp>"}  — the raw JSON-RPC response from debug_getRawBlock
///   {"block": "0x<rlp>"}  — generated by `zig build gen-example`
const BlockJson = struct {
    result: ?[]const u8 = null,
    block:  ?[]const u8 = null,
};

/// Matches the debug_executionWitness flat-pool witness format.
const WitnessJson = struct {
    state:   []const []const u8,
    codes:   []const []const u8,
    keys:    []const []const u8,
    headers: []const []const u8,
};

// ─── Public API ────────────────────────────────────────────────────────────────

pub const ParsedBlock = struct {
    number:     u64,
    state_root: [32]u8,
};

/// Find the pre-execution state root for `block_number` by scanning `headers`
/// for the parent block (number == block_number - 1) and returning its stateRoot.
///
/// `headers` contains bare RLP-encoded block headers from the witness.
/// Returns null if block_number is 0 or no matching header is found.
pub fn findPreStateRoot(headers: []const []const u8, block_number: u64) ?[32]u8 {
    if (block_number == 0) return null;
    const parent_number = block_number - 1;
    for (headers) |hdr_bytes| {
        const hdr = decodeHeaderRlp(hdr_bytes) catch continue;
        if (hdr.number == parent_number) return hdr.state_root;
    }
    return null;
}

/// Parse block.json.  Accepts either:
///   {"result":"0x<rlp>"}  — raw JSON-RPC response from debug_getRawBlock
///   {"block": "0x<rlp>"}  — generated by `zig build gen-example`
///
/// The block number and state root are extracted from header fields 8 and 3.
pub fn parseBlockJson(
    allocator: std.mem.Allocator,
    json_str:  []const u8,
) !ParsedBlock {
    const parsed = try std.json.parseFromSlice(
        BlockJson, allocator, json_str,
        .{ .ignore_unknown_fields = true },
    );
    defer parsed.deinit();

    const hex = parsed.value.result orelse parsed.value.block orelse
        return error.MissingField;
    const raw = try hexToSlice(allocator, hex);
    const hdr = try decodeBlockHeader(raw);
    return ParsedBlock{ .number = hdr.number, .state_root = hdr.state_root };
}

/// Parse witness.json — expects `{"state":[…],"codes":[…],"keys":[…],"headers":[…]}`.
///
/// All hex-decoded byte slices are allocated from `allocator`.
/// Using an arena allocator is the simplest ownership strategy.
pub fn parseWitnessJson(
    allocator: std.mem.Allocator,
    json_str:  []const u8,
) !input.StateWitness {
    // We need a temporary allocator for the parsed JSON strings — they are
    // owned by the Parsed value and freed by deinit(). The decoded byte slices
    // (nodes/codes/keys/headers) are allocated from `allocator` independently.
    const parsed = try std.json.parseFromSlice(
        WitnessJson, allocator, json_str,
        .{ .ignore_unknown_fields = true },
    );
    defer parsed.deinit();

    return input.StateWitness{
        .state_root = @splat(0), // filled in by the caller from ParsedBlock
        .nodes      = try hexSliceArray(allocator, parsed.value.state),
        .codes      = try hexSliceArray(allocator, parsed.value.codes),
        .keys       = try hexSliceArray(allocator, parsed.value.keys),
        .headers    = try hexSliceArray(allocator, parsed.value.headers),
    };
}

/// Parse a block.json + witness.json pair into a StatelessInput.
/// Convenience wrapper around parseBlockJson + parseWitnessJson.
pub fn parseBlockAndWitness(
    allocator:        std.mem.Allocator,
    block_json_str:   []const u8,
    witness_json_str: []const u8,
) !input.StatelessInput {
    const blk = try parseBlockJson(allocator, block_json_str);
    var wit   = try parseWitnessJson(allocator, witness_json_str);
    wit.state_root = blk.state_root;
    return input.StatelessInput{
        .block_number = blk.number,
        .transactions = &.{},
        .witness      = wit,
    };
}

// ─── Block RLP decoder ─────────────────────────────────────────────────────────

const BlockHeader = struct {
    number:     u64,
    state_root: [32]u8,
};

/// Decode an Ethereum block from its RLP bytes, extracting the block number
/// and state root from the block header.
///
/// Block structure: RLP([header_list, transactions, uncles, withdrawals])
///
/// Header fields:
///   0  parentHash       (32 bytes)
///   1  sha3Uncles       (32 bytes)
///   2  coinbase         (20 bytes)
///   3  stateRoot        (32 bytes)  ← extracted
///   4  transactionsRoot (32 bytes)
///   5  receiptsRoot     (32 bytes)
///   6  logsBloom        (256 bytes)
///   7  difficulty       (uint)
///   8  number           (uint)      ← extracted
fn decodeBlockHeader(raw: []const u8) error{InvalidBlock}!BlockHeader {
    // Outer block: list([header, txns, uncles, withdrawals])
    const outer_r = mpt.rlp.decodeItem(raw) catch return error.InvalidBlock;
    const block_payload = switch (outer_r.item) {
        .list  => |p| p,
        .bytes => return error.InvalidBlock,
    };

    // First item of the block list = header (also a list)
    const hdr_r = mpt.rlp.decodeItem(block_payload) catch return error.InvalidBlock;
    const hdr_payload = switch (hdr_r.item) {
        .list  => |p| p,
        .bytes => return error.InvalidBlock,
    };

    // Walk the first 9 header fields (indices 0–8) to extract stateRoot and number.
    var rest = hdr_payload;
    var state_root: [32]u8 = @splat(0);
    var number: u64 = 0;
    var i: usize = 0;
    while (i <= 8) : (i += 1) {
        if (rest.len == 0) return error.InvalidBlock;
        const r = mpt.rlp.decodeItem(rest) catch return error.InvalidBlock;
        switch (i) {
            3 => { // stateRoot
                const b = switch (r.item) { .bytes => |bts| bts, .list => return error.InvalidBlock };
                if (b.len != 32) return error.InvalidBlock;
                @memcpy(&state_root, b);
            },
            8 => { // number (minimal big-endian uint, 0–8 bytes)
                const b = switch (r.item) { .bytes => |bts| bts, .list => return error.InvalidBlock };
                if (b.len > 8) return error.InvalidBlock;
                for (b) |byte| number = (number << 8) | byte;
            },
            else => {},
        }
        rest = rest[r.consumed..];
    }

    return BlockHeader{ .number = number, .state_root = state_root };
}

/// Decode block number and state root from a bare RLP block header
/// (a plain header list, not wrapped in the outer block list).
///
/// This is used for the `headers` array in the witness, which contains
/// raw header RLP rather than full block RLP.
fn decodeHeaderRlp(raw: []const u8) error{InvalidBlock}!BlockHeader {
    const hdr_r = mpt.rlp.decodeItem(raw) catch return error.InvalidBlock;
    const hdr_payload = switch (hdr_r.item) {
        .list  => |p| p,
        .bytes => return error.InvalidBlock,
    };

    var rest = hdr_payload;
    var state_root: [32]u8 = @splat(0);
    var number: u64 = 0;
    var i: usize = 0;
    while (i <= 8) : (i += 1) {
        if (rest.len == 0) return error.InvalidBlock;
        const r = mpt.rlp.decodeItem(rest) catch return error.InvalidBlock;
        switch (i) {
            3 => {
                const b = switch (r.item) { .bytes => |bts| bts, .list => return error.InvalidBlock };
                if (b.len != 32) return error.InvalidBlock;
                @memcpy(&state_root, b);
            },
            8 => {
                const b = switch (r.item) { .bytes => |bts| bts, .list => return error.InvalidBlock };
                if (b.len > 8) return error.InvalidBlock;
                for (b) |byte| number = (number << 8) | byte;
            },
            else => {},
        }
        rest = rest[r.consumed..];
    }

    return BlockHeader{ .number = number, .state_root = state_root };
}

// ─── Helpers ───────────────────────────────────────────────────────────────────

/// Allocate a new []u8 slice decoded from a "0x…" hex string.
fn hexToSlice(allocator: std.mem.Allocator, hex: []const u8) ![]u8 {
    const s = stripHexPrefix(hex);
    if (s.len % 2 != 0) return error.OddHexLength;
    const out = try allocator.alloc(u8, s.len / 2);
    _ = try std.fmt.hexToBytes(out, s);
    return out;
}

/// Decode an array of "0x…" hex strings into an array of owned byte slices.
fn hexSliceArray(
    allocator: std.mem.Allocator,
    hexes:     []const []const u8,
) ![]const []const u8 {
    const result = try allocator.alloc([]const u8, hexes.len);
    for (hexes, 0..) |h, i| {
        result[i] = try hexToSlice(allocator, h);
    }
    return result;
}

fn stripHexPrefix(hex: []const u8) []const u8 {
    if (hex.len >= 2 and hex[0] == '0' and (hex[1] == 'x' or hex[1] == 'X'))
        return hex[2..];
    return hex;
}
