//! JSON I/O: parse block.json + witness.json into StatelessInput.
//!
//! The JSON formats:
//!
//!   block.json (any of these is accepted):
//!     { "result": "0x<hex RLP>" }  — raw JSON-RPC response from debug_getRawBlock
//!     { "block":  "0x<hex RLP>" }  — generated by `zig build gen-example`
//!
//!   witness.json:
//!     { "state":   ["0x<hex>", ...],   — flat pool of RLP trie node preimages
//!       "codes":   ["0x<hex>", ...],   — contract bytecodes
//!       "keys":    ["0x<hex>", ...],   — 20-byte addrs, 52-byte addr+slot, or 32-byte slot
//!       "headers": ["0x<hex>", ...] }  — RLP block headers for BLOCKHASH
//!
//! All hex-decoded byte slices are allocated from the provided allocator.

const std    = @import("std");
const primitives = @import("primitives");
const input  = @import("input");
const mpt    = @import("mpt");

// ─── JSON schema structs ───────────────────────────────────────────────────────

/// Accepts either:
///   {"result":"0x<rlp>"}  — the raw JSON-RPC response from debug_getRawBlock
///   {"block": "0x<rlp>"}  — generated by `zig build gen-example`
const BlockJson = struct {
    result: ?[]const u8 = null,
    block:  ?[]const u8 = null,
};

/// Witness fields in the debug_executionWitness flat-pool format.
const WitnessFields = struct {
    state:   []const []const u8,
    codes:   []const []const u8,
    keys:    []const []const u8,
    headers: []const []const u8,
};

/// Accepts either:
///   { "state":[...], "codes":[...], "keys":[...], "headers":[...] }
///     — direct witness (generated by `zig build gen-example` or older Geth)
///   { "jsonrpc":"2.0", "id":1, "result":{ "state":[...], ... } }
///     — JSON-RPC envelope from debug_executionWitness / debug_generateWitness
const WitnessJson = struct {
    // Direct fields (old format / gen-example)
    state:   ?[]const []const u8 = null,
    codes:   ?[]const []const u8 = null,
    keys:    ?[]const []const u8 = null,
    headers: ?[]const []const u8 = null,
    // JSON-RPC envelope (new format)
    result:  ?WitnessFields = null,
};

// ─── Public API ────────────────────────────────────────────────────────────────

/// Result of parsing block.json: the full Osaka header and extracted transactions.
pub const ParsedBlock = struct {
    header:       input.Header,
    transactions: []const []const u8,
};

/// Find the pre-execution state root for `block_number` by scanning `headers`
/// for the parent block (number == block_number - 1) and returning its stateRoot.
///
/// `headers` contains bare RLP-encoded block headers from the witness.
/// Returns null if block_number is 0 or no matching header is found.
pub fn findPreStateRoot(headers: []const []const u8, block_number: u64) ?[32]u8 {
    if (block_number == 0) return null;
    const parent_number = block_number - 1;
    for (headers) |hdr_bytes| {
        const hdr = decodeHeaderRlp(hdr_bytes) catch continue;
        if (hdr.number == parent_number) return hdr.state_root;
    }
    return null;
}

/// Parse block.json.  Accepts either:
///   {"result":"0x<rlp>"}  — raw JSON-RPC response from debug_getRawBlock
///   {"block": "0x<rlp>"}  — generated by `zig build gen-example`
///
/// Decodes the full Osaka block header (all 21 fields) and extracts the
/// transaction list from the block body.
pub fn parseBlockJson(
    allocator: std.mem.Allocator,
    json_str:  []const u8,
) !ParsedBlock {
    const parsed = try std.json.parseFromSlice(
        BlockJson, allocator, json_str,
        .{ .ignore_unknown_fields = true },
    );
    defer parsed.deinit();

    const hex = parsed.value.result orelse parsed.value.block orelse
        return error.MissingField;
    const raw = try hexToSlice(allocator, hex);
    return decodeBlock(allocator, raw);
}

/// Parse witness.json — expects `{"state":[…],"codes":[…],"keys":[…],"headers":[…]}`.
///
/// All hex-decoded byte slices are allocated from `allocator`.
/// Using an arena allocator is the simplest ownership strategy.
pub fn parseWitnessJson(
    allocator: std.mem.Allocator,
    json_str:  []const u8,
) !input.StateWitness {
    // We need a temporary allocator for the parsed JSON strings — they are
    // owned by the Parsed value and freed by deinit(). The decoded byte slices
    // (nodes/codes/keys/headers) are allocated from `allocator` independently.
    const parsed = try std.json.parseFromSlice(
        WitnessJson, allocator, json_str,
        .{ .ignore_unknown_fields = true },
    );
    defer parsed.deinit();

    // Unwrap the JSON-RPC envelope if present, otherwise use top-level fields.
    const fields: WitnessFields = if (parsed.value.result) |r| r else .{
        .state   = parsed.value.state   orelse return error.MissingField,
        .codes   = parsed.value.codes   orelse return error.MissingField,
        .keys    = parsed.value.keys    orelse return error.MissingField,
        .headers = parsed.value.headers orelse return error.MissingField,
    };

    return input.StateWitness{
        .state_root = @splat(0), // filled in by the caller from ParsedBlock
        .nodes      = try hexSliceArray(allocator, fields.state),
        .codes      = try hexSliceArray(allocator, fields.codes),
        .keys       = try hexSliceArray(allocator, fields.keys),
        .headers    = try hexSliceArray(allocator, fields.headers),
    };
}

/// Parse a block.json + witness.json pair into a StatelessInput.
/// Convenience wrapper around parseBlockJson + parseWitnessJson.
pub fn parseBlockAndWitness(
    allocator:        std.mem.Allocator,
    block_json_str:   []const u8,
    witness_json_str: []const u8,
) !input.StatelessInput {
    const blk = try parseBlockJson(allocator, block_json_str);
    var wit   = try parseWitnessJson(allocator, witness_json_str);
    wit.state_root = blk.header.state_root;
    return input.StatelessInput{
        .header       = blk.header,
        .transactions = blk.transactions,
        .witness      = wit,
    };
}

// ─── Block RLP decoder ─────────────────────────────────────────────────────────

/// Decode a full Ethereum block (Osaka), extracting:
///   - all 21 header fields into an Header
///   - the transaction list from the block body
///
/// Block structure: RLP([header_list, transactions_list, ommers_list, withdrawals_list])
///
/// Osaka header fields (canonical RLP order):
///   [0]  parentHash            (32 bytes)
///   [1]  sha3Uncles            (32 bytes)  always KECCAK_EMPTY_LIST in PoS
///   [2]  coinbase              (20 bytes)
///   [3]  stateRoot             (32 bytes)  post-execution
///   [4]  transactionsRoot      (32 bytes)
///   [5]  receiptsRoot          (32 bytes)
///   [6]  logsBloom             (256 bytes) skipped
///   [7]  difficulty            (uint)      always 0 for PoS
///   [8]  number                (uint)
///   [9]  gasLimit              (uint)
///   [10] gasUsed               (uint)
///   [11] timestamp             (uint)
///   [12] extraData             (bytes)     skipped
///   [13] mixHash / prevRandao  (32 bytes)
///   [14] nonce                 (8 bytes)   skipped (always 0 in PoS)
///   [15] baseFeePerGas         (uint)      EIP-1559
///   [16] withdrawalsRoot       (32 bytes)  EIP-4895
///   [17] blobGasUsed           (uint)      EIP-4844
///   [18] excessBlobGas         (uint)      EIP-4844
///   [19] parentBeaconBlockRoot (32 bytes)  EIP-4788
///   [20] requestsHash          (32 bytes)  EIP-7685
fn decodeBlock(allocator: std.mem.Allocator, raw: []const u8) !ParsedBlock {
    // Outer block: list([header, txns, ommers, withdrawals])
    const outer_r = mpt.rlp.decodeItem(raw) catch return error.InvalidBlock;
    const block_payload = switch (outer_r.item) {
        .list  => |p| p,
        .bytes => return error.InvalidBlock,
    };

    // ── Header ───────────────────────────────────────────────────────────────
    const hdr_r = mpt.rlp.decodeItem(block_payload) catch return error.InvalidBlock;
    const hdr_payload = switch (hdr_r.item) {
        .list  => |p| p,
        .bytes => return error.InvalidBlock,
    };
    const header = try decodeHeaderFields(hdr_payload);

    // ── Transactions ─────────────────────────────────────────────────────────
    const after_hdr  = block_payload[hdr_r.consumed..];
    const txns_r = mpt.rlp.decodeItem(after_hdr) catch return error.InvalidBlock;
    const txns_payload = switch (txns_r.item) {
        .list  => |p| p,
        .bytes => return error.InvalidBlock,
    };
    const transactions = try decodeTransactions(allocator, txns_payload);

    return ParsedBlock{ .header = header, .transactions = transactions };
}

/// Decode all 21 Osaka header fields from the RLP list payload (no outer wrapper).
fn decodeHeaderFields(payload: []const u8) error{InvalidBlock}!input.Header {
    var rest = payload;

    const parent_hash              = try nextHash(&rest);     // [0]
    const ommers_hash              = try nextHash(&rest);     // [1]
    const coinbase                 = try nextAddress(&rest);  // [2]
    const state_root               = try nextHash(&rest);     // [3]
    const transactions_root        = try nextHash(&rest);     // [4]
    const receipts_root            = try nextHash(&rest);     // [5]
    try skipField(&rest);                                     // [6] bloom
    const difficulty               = try nextUint256(&rest);  // [7]
    const number                   = try nextUint64(&rest);   // [8]
    const gas_limit                = try nextUint64(&rest);   // [9]
    const gas_used                 = try nextUint64(&rest);   // [10]
    const timestamp                = try nextUint64(&rest);   // [11]
    try skipField(&rest);                                     // [12] extra_data
    const prev_randao              = try nextHash(&rest);     // [13]
    try skipField(&rest);                                     // [14] nonce
    const base_fee_per_gas         = try nextUint64(&rest);   // [15]
    const withdrawals_root         = try nextHash(&rest);     // [16]
    const blob_gas_used            = try nextUint64(&rest);   // [17]
    const excess_blob_gas          = try nextUint64(&rest);   // [18]
    const parent_beacon_block_root = try nextHash(&rest);     // [19]
    // [20] requestsHash — present in Osaka/Prague; absent in Cancun blocks.
    // Use the zero hash as a safe default for pre-Osaka blocks.
    const requests_hash: primitives.Hash = if (rest.len > 0)
        try nextHash(&rest)
    else
        @splat(0);

    return input.Header{
        .parent_hash              = parent_hash,
        .ommers_hash              = ommers_hash,
        .coinbase                 = coinbase,
        .state_root               = state_root,
        .transactions_root        = transactions_root,
        .receipts_root            = receipts_root,
        .difficulty               = difficulty,
        .number                   = number,
        .gas_limit                = gas_limit,
        .gas_used                 = gas_used,
        .timestamp                = timestamp,
        .prev_randao              = prev_randao,
        .base_fee_per_gas         = base_fee_per_gas,
        .withdrawals_root         = withdrawals_root,
        .blob_gas_used            = blob_gas_used,
        .excess_blob_gas          = excess_blob_gas,
        .parent_beacon_block_root = parent_beacon_block_root,
        .requests_hash            = requests_hash,
    };
}

/// Extract transactions from the block body's transaction list payload.
///
/// Each entry is stored in canonical wire format:
///   - Legacy tx    (type 0): full RLP list bytes  (\xc?...)
///   - Typed tx (type 1–4):  type_byte || rlp_payload  (content of the RLP byte string)
fn decodeTransactions(
    allocator: std.mem.Allocator,
    payload:   []const u8,
) ![]const []const u8 {
    // First pass: count items.
    var count: usize = 0;
    var tmp = payload;
    while (tmp.len > 0) {
        const r = mpt.rlp.decodeItem(tmp) catch return error.InvalidBlock;
        count += 1;
        tmp = tmp[r.consumed..];
    }

    const txns = try allocator.alloc([]const u8, count);
    var offset: usize = 0;
    for (0..count) |i| {
        const r = mpt.rlp.decodeItem(payload[offset..]) catch return error.InvalidBlock;
        txns[i] = switch (r.item) {
            // Typed tx: the byte-string content is already type || rlp_payload.
            .bytes => |b| b,
            // Legacy tx: store the full RLP item (list prefix + payload).
            .list  => payload[offset .. offset + r.consumed],
        };
        offset += r.consumed;
    }
    return txns;
}

// ─── Bare header decoder (for witness.headers parent lookup) ───────────────────

const ParentHeader = struct {
    number:     u64,
    state_root: [32]u8,
};

/// Decode block number and state root from a bare RLP block header
/// (a plain header list, not wrapped in the outer block list).
///
/// This is used for the `headers` array in the witness, which contains
/// raw header RLP rather than full block RLP.
fn decodeHeaderRlp(raw: []const u8) error{InvalidBlock}!ParentHeader {
    const hdr_r = mpt.rlp.decodeItem(raw) catch return error.InvalidBlock;
    const hdr_payload = switch (hdr_r.item) {
        .list  => |p| p,
        .bytes => return error.InvalidBlock,
    };

    // Walk only up to field 8 (number); we only need [3]=stateRoot and [8]=number.
    var rest = hdr_payload;
    var state_root: [32]u8 = @splat(0);
    var number: u64 = 0;
    var i: usize = 0;
    while (i <= 8) : (i += 1) {
        if (rest.len == 0) return error.InvalidBlock;
        const r = mpt.rlp.decodeItem(rest) catch return error.InvalidBlock;
        switch (i) {
            3 => {
                const b = switch (r.item) { .bytes => |bts| bts, .list => return error.InvalidBlock };
                if (b.len != 32) return error.InvalidBlock;
                @memcpy(&state_root, b);
            },
            8 => {
                const b = switch (r.item) { .bytes => |bts| bts, .list => return error.InvalidBlock };
                if (b.len > 8) return error.InvalidBlock;
                for (b) |byte| number = (number << 8) | byte;
            },
            else => {},
        }
        rest = rest[r.consumed..];
    }

    return ParentHeader{ .number = number, .state_root = state_root };
}

// ─── RLP field helpers ─────────────────────────────────────────────────────────

fn nextHash(rest: *[]const u8) error{InvalidBlock}![32]u8 {
    const r = mpt.rlp.decodeItem(rest.*) catch return error.InvalidBlock;
    const b = switch (r.item) { .bytes => |bs| bs, .list => return error.InvalidBlock };
    if (b.len != 32) return error.InvalidBlock;
    var out: [32]u8 = undefined;
    @memcpy(&out, b);
    rest.* = rest.*[r.consumed..];
    return out;
}

fn nextAddress(rest: *[]const u8) error{InvalidBlock}![20]u8 {
    const r = mpt.rlp.decodeItem(rest.*) catch return error.InvalidBlock;
    const b = switch (r.item) { .bytes => |bs| bs, .list => return error.InvalidBlock };
    if (b.len != 20) return error.InvalidBlock;
    var out: [20]u8 = undefined;
    @memcpy(&out, b);
    rest.* = rest.*[r.consumed..];
    return out;
}

fn nextUint64(rest: *[]const u8) error{InvalidBlock}!u64 {
    const r = mpt.rlp.decodeItem(rest.*) catch return error.InvalidBlock;
    const b = switch (r.item) { .bytes => |bs| bs, .list => return error.InvalidBlock };
    if (b.len > 8) return error.InvalidBlock;
    var v: u64 = 0;
    for (b) |byte| v = (v << 8) | byte;
    rest.* = rest.*[r.consumed..];
    return v;
}

fn nextUint256(rest: *[]const u8) error{InvalidBlock}!u256 {
    const r = mpt.rlp.decodeItem(rest.*) catch return error.InvalidBlock;
    const b = switch (r.item) { .bytes => |bs| bs, .list => return error.InvalidBlock };
    if (b.len > 32) return error.InvalidBlock;
    var v: u256 = 0;
    for (b) |byte| v = (v << 8) | byte;
    rest.* = rest.*[r.consumed..];
    return v;
}

fn skipField(rest: *[]const u8) error{InvalidBlock}!void {
    const r = mpt.rlp.decodeItem(rest.*) catch return error.InvalidBlock;
    rest.* = rest.*[r.consumed..];
}

// ─── Hex helpers ───────────────────────────────────────────────────────────────

/// Allocate a new []u8 slice decoded from a "0x…" hex string.
fn hexToSlice(allocator: std.mem.Allocator, hex: []const u8) ![]u8 {
    const s = stripHexPrefix(hex);
    if (s.len % 2 != 0) return error.OddHexLength;
    const out = try allocator.alloc(u8, s.len / 2);
    _ = try std.fmt.hexToBytes(out, s);
    return out;
}

/// Decode an array of "0x…" hex strings into an array of owned byte slices.
fn hexSliceArray(
    allocator: std.mem.Allocator,
    hexes:     []const []const u8,
) ![]const []const u8 {
    const result = try allocator.alloc([]const u8, hexes.len);
    for (hexes, 0..) |h, i| {
        result[i] = try hexToSlice(allocator, h);
    }
    return result;
}

fn stripHexPrefix(hex: []const u8) []const u8 {
    if (hex.len >= 2 and hex[0] == '0' and (hex[1] == 'x' or hex[1] == 'X'))
        return hex[2..];
    return hex;
}
