//! JSON I/O: parse block.json + witness.json into StatelessInput.
//!
//! The JSON formats:
//!
//!   block.json (any of these is accepted):
//!     { "result": "0x<hex RLP>" }  — raw JSON-RPC response from debug_getRawBlock
//!     { "block":  "0x<hex RLP>" }  — generated by `zig build gen-example`
//!
//!   witness.json:
//!     { "state":   ["0x<hex>", ...],   — flat pool of RLP trie node preimages
//!       "codes":   ["0x<hex>", ...],   — contract bytecodes
//!       "keys":    ["0x<hex>", ...],   — 20-byte addrs, 52-byte addr+slot, or 32-byte slot
//!       "headers": ["0x<hex>", ...] }  — RLP block headers for BLOCKHASH
//!
//! All hex-decoded byte slices are allocated from the provided allocator.

const std        = @import("std");
const input      = @import("input");
const mpt        = @import("mpt");
const rlp_decode = @import("rlp_decode");

// ─── JSON schema structs ───────────────────────────────────────────────────────

/// Accepts either:
///   {"result":"0x<rlp>"}  — the raw JSON-RPC response from debug_getRawBlock
///   {"block": "0x<rlp>"}  — generated by `zig build gen-example`
const BlockJson = struct {
    result: ?[]const u8 = null,
    block:  ?[]const u8 = null,
};

/// Witness fields in the debug_executionWitness flat-pool format.
const WitnessFields = struct {
    state:   []const []const u8,
    codes:   []const []const u8,
    keys:    []const []const u8,
    headers: []const []const u8,
};

/// Accepts either:
///   { "state":[...], "codes":[...], "keys":[...], "headers":[...] }
///     — direct witness (generated by `zig build gen-example` or older Geth)
///   { "jsonrpc":"2.0", "id":1, "result":{ "state":[...], ... } }
///     — JSON-RPC envelope from debug_executionWitness / debug_generateWitness
const WitnessJson = struct {
    // Direct fields (old format / gen-example)
    state:   ?[]const []const u8 = null,
    codes:   ?[]const []const u8 = null,
    keys:    ?[]const []const u8 = null,
    headers: ?[]const []const u8 = null,
    // JSON-RPC envelope (new format)
    result:  ?WitnessFields = null,
};

// ─── Public API ────────────────────────────────────────────────────────────────

/// Result of parsing block.json: the full block header, decoded transactions, and withdrawals.
pub const ParsedBlock = struct {
    header:       input.BlockHeader,
    transactions: []const input.Transaction,
    withdrawals:  []const input.Withdrawal,
};

/// Parse block.json.  Accepts either:
///   {"result":"0x<rlp>"}  — raw JSON-RPC response from debug_getRawBlock
///   {"block": "0x<rlp>"}  — generated by `zig build gen-example`
pub fn parseBlockJson(
    allocator: std.mem.Allocator,
    json_str:  []const u8,
) !ParsedBlock {
    const parsed = try std.json.parseFromSlice(
        BlockJson, allocator, json_str,
        .{ .ignore_unknown_fields = true },
    );
    defer parsed.deinit();

    const hex = parsed.value.result orelse parsed.value.block orelse
        return error.MissingField;
    const raw = try hexToSlice(allocator, hex);
    return decodeBlock(allocator, raw);
}

/// Parse witness.json — expects `{"state":[…],"codes":[…],"keys":[…],"headers":[…]}`.
///
/// All hex-decoded byte slices are allocated from `allocator`.
pub fn parseWitnessJson(
    allocator: std.mem.Allocator,
    json_str:  []const u8,
) !input.StateWitness {
    const parsed = try std.json.parseFromSlice(
        WitnessJson, allocator, json_str,
        .{ .ignore_unknown_fields = true },
    );
    defer parsed.deinit();

    const fields: WitnessFields = if (parsed.value.result) |r| r else .{
        .state   = parsed.value.state   orelse return error.MissingField,
        .codes   = parsed.value.codes   orelse return error.MissingField,
        .keys    = parsed.value.keys    orelse return error.MissingField,
        .headers = parsed.value.headers orelse return error.MissingField,
    };

    return input.StateWitness{
        .state_root = @splat(0), // filled in by the caller from ParsedBlock
        .nodes      = try hexSliceArray(allocator, fields.state),
        .codes      = try hexSliceArray(allocator, fields.codes),
        .keys       = try hexSliceArray(allocator, fields.keys),
        .headers    = try hexSliceArray(allocator, fields.headers),
    };
}

/// Parse a block.json + witness.json pair into a StatelessInput.
/// Convenience wrapper around parseBlockJson + parseWitnessJson.
pub fn parseBlockAndWitness(
    allocator:        std.mem.Allocator,
    block_json_str:   []const u8,
    witness_json_str: []const u8,
) !input.StatelessInput {
    const blk = try parseBlockJson(allocator, block_json_str);
    var wit   = try parseWitnessJson(allocator, witness_json_str);
    wit.state_root = rlp_decode.findPreStateRoot(wit.headers, blk.header.number) orelse blk.header.state_root;
    return input.StatelessInput{
        .block        = blk.header,
        .transactions = blk.transactions,
        .witness      = wit,
        .withdrawals  = blk.withdrawals,
    };
}

/// Parse a raw RLP-encoded block (without JSON wrapping) into a ParsedBlock.
/// Used by the binary framed-stdin path.
pub fn parseBlockFromRlp(allocator: std.mem.Allocator, raw: []const u8) !ParsedBlock {
    return decodeBlock(allocator, raw);
}

// ─── Block RLP decoder ─────────────────────────────────────────────────────────

/// Decode a full Ethereum block (outer RLP wrapper) into header + transactions.
/// Block structure: RLP([header_list, transactions_list, ommers_list, withdrawals_list?])
fn decodeBlock(allocator: std.mem.Allocator, raw: []const u8) !ParsedBlock {
    const outer_r = mpt.rlp.decodeItem(raw) catch return error.InvalidBlock;
    const block_payload = switch (outer_r.item) {
        .list  => |p| p,
        .bytes => return error.InvalidBlock,
    };

    const hdr_r = mpt.rlp.decodeItem(block_payload) catch return error.InvalidBlock;
    const hdr_payload = switch (hdr_r.item) {
        .list  => |p| p,
        .bytes => return error.InvalidBlock,
    };
    const header = try rlp_decode.decodeBlockHeader(allocator, hdr_payload);

    const after_hdr = block_payload[hdr_r.consumed..];
    const txns_r = mpt.rlp.decodeItem(after_hdr) catch return error.InvalidBlock;
    const txns_payload = switch (txns_r.item) {
        .list  => |p| p,
        .bytes => return error.InvalidBlock,
    };
    const transactions = try rlp_decode.decodeTxList(allocator, txns_payload);

    // Skip ommers (uncles) list, then decode optional withdrawals.
    var withdrawals: []const input.Withdrawal = &.{};
    const after_txns = after_hdr[txns_r.consumed..];
    if (after_txns.len > 0) {
        const ommers_r = mpt.rlp.decodeItem(after_txns) catch return ParsedBlock{
            .header = header, .transactions = transactions, .withdrawals = &.{},
        };
        const after_ommers = after_txns[ommers_r.consumed..];
        if (after_ommers.len > 0) {
            const wd_r = mpt.rlp.decodeItem(after_ommers) catch return ParsedBlock{
                .header = header, .transactions = transactions, .withdrawals = &.{},
            };
            const wd_payload = switch (wd_r.item) { .list => |p| p, .bytes => &.{} };
            withdrawals = rlp_decode.decodeWithdrawals(allocator, wd_payload) catch &.{};
        }
    }

    return ParsedBlock{ .header = header, .transactions = transactions, .withdrawals = withdrawals };
}

// ─── Hex helpers ───────────────────────────────────────────────────────────────

fn hexToSlice(allocator: std.mem.Allocator, hex: []const u8) ![]u8 {
    const s = stripHexPrefix(hex);
    if (s.len % 2 != 0) return error.OddHexLength;
    const out = try allocator.alloc(u8, s.len / 2);
    _ = try std.fmt.hexToBytes(out, s);
    return out;
}

fn hexSliceArray(
    allocator: std.mem.Allocator,
    hexes:     []const []const u8,
) ![]const []const u8 {
    const result = try allocator.alloc([]const u8, hexes.len);
    for (hexes, 0..) |h, i| {
        result[i] = try hexToSlice(allocator, h);
    }
    return result;
}

fn stripHexPrefix(hex: []const u8) []const u8 {
    if (hex.len >= 2 and hex[0] == '0' and (hex[1] == 'x' or hex[1] == 'X'))
        return hex[2..];
    return hex;
}
