const std = @import("std");

const io         = @import("io.zig");
const input      = @import("input");
const primitives = @import("primitives");
const mpt        = @import("mpt");
const db         = @import("db");
const executor   = @import("executor");

pub fn main() void {
    run() catch |err| {
        std.debug.print("fatal: {}\n", .{err});
        std.process.exit(1);
    };
}

fn run() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const args = try std.process.argsAlloc(allocator);

    const block_path   = if (args.len > 1) args[1] else "examples/block.json";
    const witness_path = if (args.len > 2) args[2] else "examples/witness.json";

    const block_json = std.fs.cwd().readFileAlloc(allocator, block_path, 1 << 20) catch |err| {
        std.debug.print("error: cannot read {s}: {}\n", .{ block_path, err });
        std.debug.print("hint:  run `zig build gen-example` to create the example files.\n", .{});
        std.process.exit(1);
    };

    const witness_json = std.fs.cwd().readFileAlloc(allocator, witness_path, 64 << 20) catch |err| {
        std.debug.print("error: cannot read {s}: {}\n", .{ witness_path, err });
        std.process.exit(1);
    };

    const blk = io.parseBlockJson(allocator, block_json) catch |err| {
        std.debug.print("error: failed to parse {s}: {}\n", .{ block_path, err });
        std.debug.print("  accepted formats:\n", .{});
        std.debug.print("    {{\"result\":\"0x<rlp>\"}}  raw JSON-RPC response from debug_getRawBlock\n", .{});
        std.debug.print("    {{\"block\": \"0x<rlp>\"}}  generated by `zig build gen-example`\n", .{});
        std.process.exit(1);
    };

    var wit = io.parseWitnessJson(allocator, witness_json) catch |err| {
        std.debug.print("error: failed to parse {s}: {}\n", .{ witness_path, err });
        std.debug.print("  accepted formats:\n", .{});
        std.debug.print("    {{\"state\":[...],\"codes\":[...],\"keys\":[...],\"headers\":[...]}}  direct\n", .{});
        std.debug.print("    {{\"jsonrpc\":\"2.0\",\"result\":{{...}}}}  JSON-RPC envelope\n", .{});
        std.process.exit(1);
    };
    // Use the parent block's state root as the proof anchor.
    // The witness proves the PRE-execution state; blk.header.state_root is the
    // POST-execution state root and must not be used here.
    // Fall back to blk.header.state_root only for synthetic examples that embed
    // the proof anchor directly in the block header (no witness headers).
    wit.state_root = io.findPreStateRoot(wit.headers, blk.header.number) orelse blk.header.state_root;

    const si = input.StatelessInput{
        .header       = blk.header,
        .transactions = blk.transactions,
        .witness      = wit,
    };

    std.debug.print("=== zevm-stateless: block #{d} ===\n\n", .{si.header.number});

    // ── Phase 1: MPT proof verification ───────────────────────────────────────
    std.debug.print("Phase 1  MPT proof verification\n", .{});
    {
        // Thin wrapper so verifyProofVerbose (anytype writer) can use std.debug.print.
        const DebugWriter = struct {
            pub fn print(_: @This(), comptime fmt: []const u8, a: anytype) error{}!void {
                std.debug.print(fmt, a);
            }
        };
        const stderr = DebugWriter{};
        var phase1_ok = true;
        var current_addr: ?primitives.Address = null;

        for (si.witness.keys, 0..) |key, i| {
            if (key.len == 20) {
                var addr: primitives.Address = undefined;
                @memcpy(&addr, key[0..20]);
                current_addr = addr;

                const key_hash = mpt.keccak256(&addr);
                stderr.print("  [{d:>4}] account  0x{x}\n", .{ i, addr }) catch {};
                stderr.print("        key_hash  0x{x}\n", .{key_hash}) catch {};

                _ = mpt.verifyProofVerbose(si.witness.state_root, key_hash, si.witness.nodes, stderr) catch |e| {
                    stderr.print("        FAIL → {}\n", .{e}) catch {};
                    phase1_ok = false;
                    continue;
                };

                const result = mpt.verifyAccount(si.witness.state_root, addr, si.witness.nodes) catch unreachable;
                if (result) |a| {
                    const type_str = if (std.mem.eql(u8, &a.code_hash, &primitives.KECCAK_EMPTY))
                        "EOA" else "contract";
                    stderr.print("        → nonce={d}  balance={d}  type={s}\n", .{ a.nonce, a.balance, type_str }) catch {};
                } else {
                    stderr.print("        → (absent)\n", .{}) catch {};
                }

            } else if (key.len == 52) {
                var addr: primitives.Address = undefined;
                @memcpy(&addr, key[0..20]);
                current_addr = addr;
                var slot: primitives.Hash = undefined;
                @memcpy(&slot, key[20..52]);

                const acct = mpt.verifyAccount(si.witness.state_root, addr, si.witness.nodes) catch |e| {
                    stderr.print("  [{d:>4}] FAIL account 0x{x} (storage) → {}\n", .{ i, addr, e }) catch {};
                    phase1_ok = false;
                    continue;
                };
                if (acct) |a| {
                    const slot_key_hash = mpt.keccak256(&slot);
                    stderr.print("  [{d:>4}] storage  0x{x}  slot=0x{x}\n", .{ i, addr, slot }) catch {};
                    stderr.print("        storage_root  0x{x}\n", .{a.storage_root}) catch {};
                    stderr.print("        key_hash      0x{x}\n", .{slot_key_hash}) catch {};
                    _ = mpt.verifyProofVerbose(a.storage_root, slot_key_hash, si.witness.nodes, stderr) catch |e| {
                        stderr.print("        FAIL → {}\n", .{e}) catch {};
                        phase1_ok = false;
                        continue;
                    };
                    const value = mpt.verifyStorage(a.storage_root, slot, si.witness.nodes) catch unreachable;
                    stderr.print("        → value=0x{x}\n", .{value}) catch {};
                } else {
                    stderr.print("  [{d:>4}] storage  0x{x}  slot=0x{x}  value=0  (account absent)\n", .{ i, addr, slot }) catch {};
                }

            } else if (key.len == 32) {
                var slot: primitives.Hash = undefined;
                @memcpy(&slot, key[0..32]);

                if (current_addr) |addr| {
                    const acct = mpt.verifyAccount(si.witness.state_root, addr, si.witness.nodes) catch |e| {
                        stderr.print("  [{d:>4}] FAIL account 0x{x} (storage) → {}\n", .{ i, addr, e }) catch {};
                        phase1_ok = false;
                        continue;
                    };
                    if (acct) |a| {
                        const slot_key_hash = mpt.keccak256(&slot);
                        stderr.print("  [{d:>4}] storage  0x{x}  slot=0x{x}\n", .{ i, addr, slot }) catch {};
                        stderr.print("        storage_root  0x{x}\n", .{a.storage_root}) catch {};
                        stderr.print("        key_hash      0x{x}\n", .{slot_key_hash}) catch {};
                        _ = mpt.verifyProofVerbose(a.storage_root, slot_key_hash, si.witness.nodes, stderr) catch |e| {
                            stderr.print("        FAIL → {}\n", .{e}) catch {};
                            phase1_ok = false;
                            continue;
                        };
                        const value = mpt.verifyStorage(a.storage_root, slot, si.witness.nodes) catch unreachable;
                        stderr.print("        → value=0x{x}\n", .{value}) catch {};
                    } else {
                        stderr.print("  [{d:>4}] storage  0x{x}  slot=0x{x}  value=0  (account absent)\n", .{ i, addr, slot }) catch {};
                    }
                } else {
                    stderr.print("  [{d:>4}] SKIP slot 0x{x} (no preceding account key)\n", .{ i, slot }) catch {};
                }

            } else {
                stderr.print("  [{d:>4}] SKIP key with unexpected length {d}\n", .{ i, key.len }) catch {};
            }
        }

        if (!phase1_ok) std.process.exit(1);
    }
    std.debug.print(
        "  OK     root = 0x{x}\n" ++
        "         {d} node(s) in pool, {d} key(s) verified\n\n",
        .{ si.witness.state_root, si.witness.nodes.len, si.witness.keys.len },
    );

    // ── Phase 2: WitnessDatabase queries ──────────────────────────────────────
    std.debug.print("Phase 2  WitnessDatabase queries\n", .{});

    var account_count: usize = 0;
    for (si.witness.keys) |key| {
        if (key.len != 20) continue;
        account_count += 1;

        var addr: primitives.Address = undefined;
        @memcpy(&addr, key[0..20]);

        const account_state = mpt.verifyAccount(si.witness.state_root, addr, si.witness.nodes) catch |err| {
            std.debug.print("  0x{x}  error: {}\n", .{ addr, err });
            continue;
        };

        if (account_state) |a| {
            const code_desc = if (std.mem.eql(u8, &a.code_hash, &primitives.KECCAK_EMPTY))
                "EOA" else "contract";
            std.debug.print(
                "  0x{x}  nonce={d}  balance={d}  type={s}  code_hash=0x{x}  storage_root=0x{x}\n",
                .{ addr, a.nonce, a.balance, code_desc, a.code_hash, a.storage_root },
            );
        } else {
            std.debug.print("  0x{x}  (absent from trie)\n", .{addr});
        }
    }

    if (account_count == 0) {
        std.debug.print("  (no account keys in witness)\n", .{});
    }

    // ── Phase 3: Block execution ───────────────────────────────────────────────
    std.debug.print("\nPhase 3  Block execution\n", .{});
    {
        const block_env = executor.blockEnvFromHeader(si.header);

        std.debug.print("  block env\n", .{});
        std.debug.print("    number      = {d}\n",   .{block_env.number});
        std.debug.print("    coinbase    = 0x{x}\n", .{block_env.beneficiary});
        std.debug.print("    timestamp   = {d}\n",   .{block_env.timestamp});
        std.debug.print("    gas_limit   = {d}\n",   .{block_env.gas_limit});
        std.debug.print("    basefee     = {d}\n",   .{block_env.basefee});
        std.debug.print("    prevrandao  = 0x{x}\n", .{block_env.prevrandao orelse [_]u8{0} ** 32});
        if (block_env.blob_excess_gas_and_price) |b| {
            std.debug.print("    excess_blob_gas = {d}  blob_gasprice = {d}\n",
                .{ b.excess_blob_gas, b.blob_gasprice });
        }

        std.debug.print("  transactions  = {d}\n", .{si.transactions.len});

        const proof_out = executor.executeBlock(allocator, si) catch |err| {
            std.debug.print("  FAIL → {}\n", .{err});
            std.process.exit(1);
        };

        std.debug.print("  pre_state_root  = 0x{x}\n", .{proof_out.pre_state_root});

        const state_ok    = std.mem.eql(u8, &proof_out.post_state_root, &si.header.state_root);
        const receipts_ok = std.mem.eql(u8, &proof_out.receipts_root,   &si.header.receipts_root);

        if (state_ok) {
            std.debug.print("  post_state_root = 0x{x}  ✓\n", .{proof_out.post_state_root});
        } else {
            std.debug.print("  post_state_root = 0x{x}  ✗  MISMATCH\n", .{proof_out.post_state_root});
            std.debug.print("  expected        = 0x{x}\n",               .{si.header.state_root});
        }

        if (receipts_ok) {
            std.debug.print("  receipts_root   = 0x{x}  ✓\n", .{proof_out.receipts_root});
        } else {
            std.debug.print("  receipts_root   = 0x{x}  ✗  MISMATCH\n", .{proof_out.receipts_root});
            std.debug.print("  expected        = 0x{x}\n",               .{si.header.receipts_root});
        }

        if (!state_ok or !receipts_ok) {
            std.debug.print("\nFAIL\n", .{});
            std.process.exit(1);
        }
    }

    std.debug.print("\nOK\n", .{});
}
