const std = @import("std");

const io         = @import("io.zig");
const input      = @import("input");
const primitives = @import("primitives");
const mpt        = @import("mpt");
const db         = @import("db");

pub fn main() void {
    run() catch |err| {
        std.debug.print("fatal: {}\n", .{err});
        std.process.exit(1);
    };
}

fn run() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const args = try std.process.argsAlloc(allocator);

    const block_path   = if (args.len > 1) args[1] else "examples/block.json";
    const witness_path = if (args.len > 2) args[2] else "examples/witness.json";

    const block_json = std.fs.cwd().readFileAlloc(allocator, block_path, 1 << 20) catch |err| {
        std.debug.print("error: cannot read {s}: {}\n", .{ block_path, err });
        std.debug.print("hint:  run `zig build gen-example` to create the example files.\n", .{});
        std.process.exit(1);
    };

    const witness_json = std.fs.cwd().readFileAlloc(allocator, witness_path, 64 << 20) catch |err| {
        std.debug.print("error: cannot read {s}: {}\n", .{ witness_path, err });
        std.process.exit(1);
    };

    const blk = io.parseBlockJson(allocator, block_json) catch |err| {
        std.debug.print("error: failed to parse {s}: {}\n", .{ block_path, err });
        std.debug.print("  accepted formats:\n", .{});
        std.debug.print("    {{\"result\":\"0x<rlp>\"}}  raw JSON-RPC response from debug_getRawBlock\n", .{});
        std.debug.print("    {{\"block\": \"0x<rlp>\"}}  generated by `zig build gen-example`\n", .{});
        std.process.exit(1);
    };

    var wit = io.parseWitnessJson(allocator, witness_json) catch |err| {
        std.debug.print("error: failed to parse {s}: {}\n", .{ witness_path, err });
        std.debug.print("  expected format: {{\"state\":[...],\"codes\":[...],\"keys\":[...],\"headers\":[...]}}\n", .{});
        std.process.exit(1);
    };
    // Use the parent block's state root as the proof anchor.
    // The witness proves the PRE-execution state; blk.state_root is the
    // POST-execution state root and must not be used here.
    // Fall back to blk.state_root only for synthetic examples that embed
    // the proof anchor directly in the block header (no witness headers).
    wit.state_root = io.findPreStateRoot(wit.headers, blk.number) orelse blk.state_root;

    const si = input.StatelessInput{
        .block_number = blk.number,
        .transactions = &.{},
        .witness      = wit,
    };

    std.debug.print("=== zevm-stateless: block #{d} ===\n\n", .{si.block_number});

    // ── Phase 1: MPT proof verification ───────────────────────────────────────
    std.debug.print("Phase 1  MPT proof verification\n", .{});
    const proven_root = mpt.verifyWitness(si.witness) catch |err| {
        std.debug.print("  FAILED: {}\n\n", .{err});
        std.debug.print("  state root: 0x{x}\n", .{si.witness.state_root});
        std.debug.print("  pool:       {d} node(s)\n", .{si.witness.nodes.len});
        std.debug.print("  keys:       {d}\n\n", .{si.witness.keys.len});

        // Re-run key-by-key to find the first failure.
        for (si.witness.keys, 0..) |key, i| {
            if (key.len == 20) {
                var addr: primitives.Address = undefined;
                @memcpy(&addr, key[0..20]);
                if (mpt.verifyAccount(si.witness.state_root, addr, si.witness.nodes)) |_| {
                    std.debug.print("  [{d:>4}] OK   account 0x{x}\n", .{ i, addr });
                } else |e| {
                    std.debug.print("  [{d:>4}] FAIL account 0x{x}  → {}\n", .{ i, addr, e });
                }
            } else if (key.len == 52) {
                var addr: primitives.Address = undefined;
                @memcpy(&addr, key[0..20]);
                var slot: primitives.Hash = undefined;
                @memcpy(&slot, key[20..52]);
                const acct = mpt.verifyAccount(si.witness.state_root, addr, si.witness.nodes) catch |e| {
                    std.debug.print("  [{d:>4}] FAIL account 0x{x} (storage lookup) → {}\n", .{ i, addr, e });
                    continue;
                };
                const storage_root = if (acct) |as| as.storage_root else {
                    std.debug.print("  [{d:>4}] OK   storage 0x{x} slot 0x{x} = 0 (account absent)\n", .{ i, addr, slot });
                    continue;
                };
                if (mpt.verifyStorage(storage_root, slot, si.witness.nodes)) |_| {
                    std.debug.print("  [{d:>4}] OK   storage 0x{x} slot 0x{x}\n", .{ i, addr, slot });
                } else |e| {
                    std.debug.print("  [{d:>4}] FAIL storage 0x{x} slot 0x{x} → {}\n", .{ i, addr, slot, e });
                }
            } else {
                std.debug.print("  [{d:>4}] SKIP key with unexpected length {d}\n", .{ i, key.len });
            }
        }
        std.process.exit(1);
    };
    std.debug.print(
        "  OK     root = 0x{x}\n",
        .{proven_root},
    );
    std.debug.print(
        "         {d} node(s) in pool, {d} key(s) verified\n\n",
        .{ si.witness.nodes.len, si.witness.keys.len },
    );

    // ── Phase 2: WitnessDatabase queries ──────────────────────────────────────
    std.debug.print("Phase 2  WitnessDatabase queries\n", .{});
    var witness_db = db.WitnessDatabase.init(si.witness);

    var account_count: usize = 0;
    for (si.witness.keys) |key| {
        if (key.len != 20) continue;
        account_count += 1;

        var addr: primitives.Address = undefined;
        @memcpy(&addr, key[0..20]);

        const info = witness_db.basic(addr) catch |err| {
            std.debug.print(
                "  0x{x}  error: {}\n",
                .{ addr, err },
            );
            continue;
        };

        if (info) |a| {
            const code_desc = if (std.mem.eql(u8, &a.code_hash, &primitives.KECCAK_EMPTY))
                "EOA" else "contract";
            std.debug.print(
                "  0x{x}  nonce={d}  balance={d}  type={s}\n",
                .{ addr, a.nonce, a.balance, code_desc },
            );
        } else {
            std.debug.print(
                "  0x{x}  (absent from trie)\n",
                .{addr},
            );
        }
    }

    if (account_count == 0) {
        std.debug.print("  (no account keys in witness)\n", .{});
    }

    std.debug.print("\nDone.\n", .{});
}
